### ISSUE TITLE
Not working with Processing 3 

### ISSUE THREAD

**Issue by Cvcolod** [Sephen/svgtogcode#1]
Hello Sephen,

Thanks for the Code, It seems like it's not working on Processing 3 do you have by chance an update or know how to fix it ? I'm trying to do a script which convert a SVG or PDF to GCODE.

Thanks and Best,

David

**Comment by Sephen** [comment]
Hi David,

Sorry, but the code is "As is". I'm not planning in updating this code.

Regards,

Sephen
